### ISSUE TITLE
Funny

### ISSUE THREAD

**Issue by goxofy** [RealPeha/This-Repo-Has-1550-Stars#1]

**Comment by gaoryrt** [comment]
But how?
I mean, how?

**Comment by kayodesu** [comment]
This was my first thought.

**Comment by Sora233** [comment]
hahah, nice work guys.

**Comment by webxmsj** [comment]
interesting

**Comment by LighghtEeloo** [comment]
Funny indeed╰(*°▽°*)╯

**Comment by z0gSh1u** [comment]
interesting

**Comment by verils** [comment]
I thought it was keep the repo name constantly, and stars is a constant value too. That's awesome if it can be true.

**Comment by alirezainjasttt** [comment]
> But how?
> I mean, how?

@gaoryrt 
using https://github.com/octokit/rest.js/ it will check every 1000ms(1second) for how much start it has. and then I will rename the repo...

**Comment by alirezainjasttt** [comment]
> But how?
> I mean, how?

@gaoryrt 
using https://github.com/octokit/rest.js/ it will check every 1000ms(1second) for how much start it has. and then rename the repo...
